[package]
name = "minerust"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
glam = "0.21.3"
glow = "0.11.2"
hecs = "0.9.0"