[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.37.0"
glam = "0.29.0"
glow = "0.14.2"
hecs = "0.10.5"
image = "0.25.2"